name: Build and deploy Python app to Azure Web App - DIYoraaa

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        shell: powershell
        run: |
          python -m venv venv
          .\venv\Scripts\Activate.ps1

      - name: Install dependencies
        shell: powershell
        run: pip install -r requirements.txt

      - name: Create zip artifact for deployment
        shell: powershell
        run: Compress-Archive -Path * -DestinationPath release.zip -Force

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/
